#!/usr/bin/python3
from sys import argv

def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize(num):
    factors = []
    divisor = 2
    while num != 1:
        while num % divisor == 0:
            factors.append(divisor)
            num //= divisor
        divisor += 1
    return factors

with open(argv[1]) as f:
    for line in f:
        num = int(line.strip())
        print("{}=".format(num), end='')
        if is_prime(num):
            print("{}*1".format(num))
        else:
            factors = factorize(num)
            print("*".join(map(str, factors)))
